module.exports = {
  apps: [
    {
      name: 'filmstack-festival-api',
      script: 'dist/server.js',
      cwd: './apps/festival-api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/festival-api-error.log',
      out_file: './logs/festival-api-out.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
    },
    {
      name: 'filmstack-streaming-api',
      script: 'src/server.js',
      cwd: './apps/streaming-api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: './logs/streaming-api-error.log',
      out_file: './logs/streaming-api-out.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
    },
  ],
};
